const BaseCommand = require('../../utils/structures/BaseCommand');

module.exports = class ClashTips extends BaseCommand {
  constructor() {
    super('clashtips', 'clash', ['tip', 'clashtip', 'tips', 'clashtips']);
  }

  run(client, message, args) {
    const tips = ["Upgrade your cannons to improve your defense against intruders.",
      "Taking a break from Clash of Clans? Buy a Shield to protect your trophies!",
      "Improve your army! Build the Laboratory and upgrade your troops.",
      "Out of gold? Try upgrading your gold mines.",
      "Upgrade your Army Camps to build a massive army!",
      "Upgrade your walls to slow down the enemy.",
      "Defensive buildings like Cannons can't shoot while they are being upgraded.",
      "Gold Mines and Elixir Collectors do not generate resources while they are being upgraded.",
      "Even if your village is completely destroyed, you always keep some of your Gold and Elixir.",
      "Building good defenses is just as important as aggressive attacking.",
      "Barbarians tend to attack the nearest thing, regardless of building type.",
      "Archers attack anything in their range.",
      "Goblins are greedy for Gold and Elixir. Their favorite targets are resource buildings.",
      "Goblins deal double damage to resource buildings.",
      "Giants prefer to attack defensive structures like Cannons.",
      "Giants can take a lot of damage. Deploy them first to draw the defenders' attention.",
      "Wall Breakers blast holes into walls, opening a way to attack to enemy buildings.",
      "Wall Breakers deal major damage to enemy walls, but blow up themselves in the process.",
      "Balloons primarily target enemy defenses like Cannons.",
      "The Balloon is a flying unit, which means that Cannons and Mortars can't target it.",
      "Wizards can dish out high damage, but can't take much in return.",
      "Healers can heal your ground units, but won't attack enemies.",
      "The Healer is a flying unit. Air Defenses and Archer Towers can shoot her down quickly.",
      "The Dragon is a mighty flying unit that can attack both ground and air targets.",
      "Is P.E.K.K.A a knight? A samurai? A robot? No one knows!",
      "The armor on P.E.K.K.A. is so heavy that the Spring Trap does not work on her.",
      "Cannons can only shoot at ground units.",
      "Mortars can only shoot at ground targets.",
      "Mortars deal splash damage to all ground units near the hit location.",
      "Archer Towers can target both air and ground units.",
      "Air Defense's rockets only work against flying units.",
      "The Wizard Tower deals damage against all units in the target area.",
      "The Wizard Tower can target both ground and air units.",
      "The Hidden Tesla tower is hidden from attackers until they come close enough.",
      "The Hidden Tesla can attack both air and ground units.",
      "Traps are hidden from the attackers until they get close enough.",
      "Clearing obstacles like rocks and trees sometimes rewards you with Gems.",
      "The Battle Log shows information about attacks against your village.",
      "You can watch Battle Replays from the Battle Log!",
      "Destroying an enemy's Town Hall always gives you one star.",
      "Troops in the Clan Castle will defend your village.",
      "Troops in the Camps are for attacking only - they won't defend your village.",
      "An active Shield protects you from attacks, though attacking others will shorten it.",
      "You get a free Shield if an attacker destroys your village.",
      "You get a longer lasting Shield if your village takes a lot of damage.",
      "If you attack another player while you have an active Shield, you will lose a few hours of the Shield.",
      "You can attack the Goblin Horde (play single player missions) without losing your active Shield.",
      "Need a bit more gold for an upgrade? Take it from the Goblins in a single player mission!",
      "Trophies that you win are deducted from your opponents' trophies!",
      "Complete Achievements to earn free Green Gems!",
      "Upgrade your Town Hall to unlock new buildings and new upgrade levels for your current buildings.",
      "Rebuild the ruined Clan Castle to join forces with other players!",
      "Use the Clan Castle to request reinforcements from your Clanmates!",
      "Clan Castle reinforcement troops can defend your village from an enemy attack, or you can deploy them when attacking.",
      "The Lightning Spell damages units and buildings in a small area.",
      "The Healing Spell creates a ring of healing that heals your units while inside.",
      "The Rage Spell creates a ring of rage that makes your units stronger and faster while inside.",
      "The Jump Spell creates a temporary path over enemy walls for your troops to follow.",
      "Try using the Jump Spell to redirect melee troops who are busy attacking a wall!",
      "Join the Clash of Clans Forums! Look in Settings - More.",
      "You can upgrade your troops in the Laboratory to make them better and stronger!",
      "The Damage statistic in unit and turret info is measured as Damage Per Second.",
      "You can't cancel upgrades in the Laboratory once they are started. Plan ahead!",
      "Camps, Clan Castles and Storages remain functional while they are being upgraded.",
      "You can end a battle and be victorious when you have won at least one star in it.",
      "If you see an offensive message in the chat, tap it and choose 'Report' to report the player.",
      "Use chat reporting only when necessary - don't get carried away!",
      "Revenge attack is unavailable against players that you attacked first.",
      "The battle ends when you have expended all your troops, clan reinforcements and damaging spells.",
      "Upgrading your Town Hall will grant you access to a new defensive weapon called X-Bow.",
      "You can set the X-Bow to attack both air and ground targets at a short range.",
      "You can set the X-Bow to attack only ground targets at long range.",
      "X-Bow uses Elixir as ammo. Remember to reload it after enemy attacks!",
      "You can Boost the production rate of Gold Mines and Elixir Collectors with Gems once they are upgraded to level 5.",
      "You can Boost the production rate of Spell Factory with Gems.",
      "You can Boost the training speed of Barracks with Gems.",
      "Spells can have a huge effect on the outcome of the battle. Be sure to use them!",
      "You can use Dark Elixir to summon the mightiest Heroes in the realm!",
      "Dark Elixir can be stored and produced starting with Town Hall 7, along with Dark Elixir troops!",
      "You can start looting Dark Elixir as soon as you have built the storage for it.",
      "Your Hero can attack enemy villages or guard yours against enemy attacks.",
      "Heroes are immortal, but they can be injured and must be healed before they can fight again.",
      "Heal your hero by letting him sleep or by using the Heal button.",
      "The Barbarian King is the strongest of them all. His consumption of Dark Elixir has made him grow bigger than Giants.",
      "The Archer Queen is an eagle-eyed warrior who wields a modified, miniature X-Bow.",
      "Want more loot? Join a League and get a Loot Bonus for every successful attack!",
      "If you have enough trophies, attacking any village will automatically place you in a League.",
      "Earn more trophies to move up to a higher League level. Higher level Leagues give better Loot Bonuses!",
      "If you lose too many trophies, you can get demoted to a lower League. Fight for those trophies!",
      "Each League Season lasts for one month.",
      "Clan tournament and troop donation counts reset every one month.",
      "Upgrade the Jump Spell to give your units more time to jump over walls.",
      "The Freeze Spell prevents buildings and troops from defending within its radius.",
      "Upgrade the Freeze Spell to disable defenses and troops for a longer time.",
      "The Inferno Tower can deal devastating damage to units it stays focused on.",
      "The Inferno Tower damage rate resets to the minimum each time it switches targets.",
      "The Inferno Tower burns Dark Elixir to power its flame. Be sure to keep it fully loaded!",
      "Never give out your Google credientials or Game Center password to anyone.",
      "Supercell employees will never ask you for your Google account or Game Center password.",
      "Seeking Air Mines do not detect Minions.",
      "Easily reorganize your village with the Village Edit Mode.",
      "Traps and bombs need to be re-armed after they have been used.",
      "Be sure to upgrade your traps to keep unwanted visitors off your lawn.",
      "Sign in using your Google Play or Game Center account to safeguard your progress.",
      "Heroes have upgradable special abilities that unlock at level 5 and can be used while attacking.",
      "Join Clan Wars for exciting battles and extra loot!",
      "You can't change the name of your village. Your villagers wouldn't know where they live!",
      "All resource storages are immune to spell damage!",
      "Haste Spells are great on troops with high damage but low speed, like Balloons or P.E.K.K.A.",
      "Earthquake Spells can heavily punish tight groups of buildings with high hitpoints.",
      "Repeated Earthquake Spells deal less damage to the same buildings.",
      "Poison Spells are very effective against large groups of enemy skeletons.",
      "Your army will fight much more effectively against Clan Castle troops inside a Poison Spell.",
      "You can activate a profanity filter for clan chat from the Settings menu.",
      "Dark Spells can take less storage space than regular Spells, allowing you to take more of them!",
      "You get some Guard each time a Shield runs out. This is a great time to attack!",
      "The higher your League, the more Guard you get whenever a Shield runs out!",
      "You can attack all you want without losing any of your active Guard.",
      "A small squad of troops can help prepare an attack before the Eagle Artillery will activate.",
      "A quick strike can overwhelm the Eagle Artillery before it does much damage.",
      "Eagle Artillery has a large no-fire zone around it. Be sure it covers your most valuable buildings!",
      "The Grand Warden harnesses mysterious artifacts to make nearby troops tough as nails.",
      "Using an flying army? Try setting the Grand Warden to air mode!",
      "The Eagle Artillery targets the toughest troops of the nearest or biggest group.",
      "A reticle appears where the Eagle Artillery's shots will land.",
      "Units near an artillery impact will take some shockwave damage.",
      "An active Guard protects you from attacks and lets you freely attack others!",
      "The Treasury protects Clan War and Star Bonus loot in the Clan Castle.",
      "Collect Loot Carts to recover resources lost on defense.",
      "Earn a Star Bonus every day by winning multiplayer battles.",
      "Earn bigger Star Bonuses at higher Leagues!",
      "Use the boat on your shores to access the Builder Base!",
      "Unlock and upgrade special abilities for your troops in the Star Laboratory.",
      "Resources in your Builder Base can not be stolen by enemies.",
      "Lower an Archer Tower to double its stopping power in a smaller range.",
      "Want to change your strategy before attacking? Tap the green arrows to swap troops!",
      "Rebuild the Gem Mine to start collecting extra Gems!",
      "Mines and Mega Mines can be set to damage either ground or air troops.",
      "Rotate Push Traps to toss troops in the direction you want.",
      "Crushers devastate ground troops, but flying or ranged troops can destroy them unharmed.",
      "Boost construction, resource production and everything else with the Clock Tower!",
      "Deploy Beta Minions far from enemy buildings to utilize their Long Shot ability.",
      "Rebuild the Battle Machine to use this powerful Hero in your attacks!",
      "The Battle Machine's Electric Hammer ability can be used again after it recharges!",
      "Look for a Gear Up option in your home village defenses to apply special upgrades from the Master Builder!",
      "Earn more Stars to win a Versus Battle! Destruction percentage is the tiebreaker.",
      "Win more Trophies to increase your Versus Battle rewards!",
      "Win 3 Versus Battles a day to get a big loot bonus.",
      "Having trouble winning Versus Battles? Watch replays and try to improve your defense!"
    ];
    const randomTipIndex = Math.floor(Math.random() * tips.length);
    let index = parseInt(args[0]);
    if (index >= 1 && index <= tips.length) {
      let tipEmbed = {
        color: `RANDOM`,
        title: 'Clash of Clans Tip #' + (index),
        description: tips[index - 1],
        thumbnail: {
          url: 'https://vignette.wikia.nocookie.net/clashofclans/images/6/61/Villager_info.png/revision/latest/scale-to-width-down/340?cb=20200622145823',
        },
        timestamp: new Date()
      };
      message.channel.send({
        embed: tipEmbed
      });
    } else {
      let tipEmbed = {
        color: `RANDOM`,
        title: 'Clash of Clans Tip #' + (randomTipIndex + 1),
        description: tips[randomTipIndex],
        thumbnail: {
          url: 'https://vignette.wikia.nocookie.net/clashofclans/images/6/61/Villager_info.png/revision/latest/scale-to-width-down/340?cb=20200622145823',
        },
        timestamp: new Date()
      };
      message.channel.send({
        embed: tipEmbed
      });
    }
  }
}